### ISSUE TITLE
README.md is missing in pip package 3.0.1

### ISSUE THREAD

**Issue by cehbrecht** [cedadev/cf-checker#21]
tried to install the latest cfchecker 3.0.1 but the required `README.md` is not in the package:
```
$ pip install cfchecker
Collecting cfchecker
  Downloading cfchecker-3.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Q2o7y6/cfchecker/setup.py", line 6, in <module>
        __description__ = "\n" + open(os.path.join(os.path.dirname(__file__), 'README.md')).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-Q2o7y6/cfchecker/README.md'
```

You need to update the ``MANIFEST.in``.

**Comment by cehbrecht** [comment]
fixed in version 3.0.4
